<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRhZbLN8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRhZbLN8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRhZbLN8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRhZbLN8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRhZbLN8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RhZbLN8',
    'container.build_id' => '53162af0',
    'container.build_time' => 1593776070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRhZbLN8');
